Add preliminary support for the ROG Crosshair X670E Hero.
zeule/asus-ec-sensors pull request #40
Opened 2023-04-25 05:59 UTC by kyndigen

Only the temp sensors that I can verify are present.  HWINFO in Windows shows other accumulated data and statistics (time since installed, total power used, etc) that I have not attempted to find.

Resolves #39.

2023-04-25 07:05 UTC, zeule requested changes
Thank you! Could you make one little change to naming, please, to make the new sensor name precise?

2023-04-25 07:05 UTC, zeule commented on asus-ec-sensors.c
> +	ec_sensor_temp_package,
`ec_sensor_temp_cpu_package`, please.

2023-04-25 07:05 UTC, zeule commented on asus-ec-sensors.c
> +#define SENSOR_TEMP_PACKAGE BIT(ec_sensor_temp_package)
Likewise, `SENSOR_TEMP_CPU_PACKAGE`.

2023-04-26 06:41 UTC, zeule approved these changes

2023-04-26 06:42 UTC, merged

2023-04-26 06:45 UTC, zeule commented
Thank you! Do you plan to look for those sensors you mentioned in the near future, or shall I submit this upstream as is? 6.4 merge window is still open, AFAIK.

2023-04-26 06:59 UTC, kyndigen commented
Go ahead and upstream it as-is.  I'm not going to have much bandwidth to do further digging for a while.